# permissions for end users to edit os.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: os-editor-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - os
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - os/status
  verbs:
  - get
